//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlumniManagement.Frontend.AlumniImageService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ImageDTO", Namespace="http://schemas.datacontract.org/2004/07/AlumniManagement.WCF.Entities")]
    [System.SerializableAttribute()]
    public partial class ImageDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AlumniIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ImageIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImagePathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UploadDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AlumniID {
            get {
                return this.AlumniIDField;
            }
            set {
                if ((this.AlumniIDField.Equals(value) != true)) {
                    this.AlumniIDField = value;
                    this.RaisePropertyChanged("AlumniID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName {
            get {
                return this.FileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FileNameField, value) != true)) {
                    this.FileNameField = value;
                    this.RaisePropertyChanged("FileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ImageID {
            get {
                return this.ImageIDField;
            }
            set {
                if ((this.ImageIDField.Equals(value) != true)) {
                    this.ImageIDField = value;
                    this.RaisePropertyChanged("ImageID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImagePath {
            get {
                return this.ImagePathField;
            }
            set {
                if ((object.ReferenceEquals(this.ImagePathField, value) != true)) {
                    this.ImagePathField = value;
                    this.RaisePropertyChanged("ImagePath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UploadDate {
            get {
                return this.UploadDateField;
            }
            set {
                if ((this.UploadDateField.Equals(value) != true)) {
                    this.UploadDateField = value;
                    this.RaisePropertyChanged("UploadDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AlumniImageService.IAlumniImageService")]
    public interface IAlumniImageService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumniImageService/GetAllImage", ReplyAction="http://tempuri.org/IAlumniImageService/GetAllImageResponse")]
        AlumniManagement.Frontend.AlumniImageService.ImageDTO[] GetAllImage(int alumniId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumniImageService/GetAllImage", ReplyAction="http://tempuri.org/IAlumniImageService/GetAllImageResponse")]
        System.Threading.Tasks.Task<AlumniManagement.Frontend.AlumniImageService.ImageDTO[]> GetAllImageAsync(int alumniId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumniImageService/GetImageById", ReplyAction="http://tempuri.org/IAlumniImageService/GetImageByIdResponse")]
        AlumniManagement.Frontend.AlumniImageService.ImageDTO GetImageById(int imageId, int alumniId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumniImageService/GetImageById", ReplyAction="http://tempuri.org/IAlumniImageService/GetImageByIdResponse")]
        System.Threading.Tasks.Task<AlumniManagement.Frontend.AlumniImageService.ImageDTO> GetImageByIdAsync(int imageId, int alumniId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumniImageService/DeleteImageById", ReplyAction="http://tempuri.org/IAlumniImageService/DeleteImageByIdResponse")]
        void DeleteImageById(int imageId, int alumniId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumniImageService/DeleteImageById", ReplyAction="http://tempuri.org/IAlumniImageService/DeleteImageByIdResponse")]
        System.Threading.Tasks.Task DeleteImageByIdAsync(int imageId, int alumniId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumniImageService/AddImage", ReplyAction="http://tempuri.org/IAlumniImageService/AddImageResponse")]
        void AddImage(AlumniManagement.Frontend.AlumniImageService.ImageDTO[] imageDTO, int alumniId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumniImageService/AddImage", ReplyAction="http://tempuri.org/IAlumniImageService/AddImageResponse")]
        System.Threading.Tasks.Task AddImageAsync(AlumniManagement.Frontend.AlumniImageService.ImageDTO[] imageDTO, int alumniId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAlumniImageServiceChannel : AlumniManagement.Frontend.AlumniImageService.IAlumniImageService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AlumniImageServiceClient : System.ServiceModel.ClientBase<AlumniManagement.Frontend.AlumniImageService.IAlumniImageService>, AlumniManagement.Frontend.AlumniImageService.IAlumniImageService {
        
        public AlumniImageServiceClient() {
        }
        
        public AlumniImageServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AlumniImageServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlumniImageServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlumniImageServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AlumniManagement.Frontend.AlumniImageService.ImageDTO[] GetAllImage(int alumniId) {
            return base.Channel.GetAllImage(alumniId);
        }
        
        public System.Threading.Tasks.Task<AlumniManagement.Frontend.AlumniImageService.ImageDTO[]> GetAllImageAsync(int alumniId) {
            return base.Channel.GetAllImageAsync(alumniId);
        }
        
        public AlumniManagement.Frontend.AlumniImageService.ImageDTO GetImageById(int imageId, int alumniId) {
            return base.Channel.GetImageById(imageId, alumniId);
        }
        
        public System.Threading.Tasks.Task<AlumniManagement.Frontend.AlumniImageService.ImageDTO> GetImageByIdAsync(int imageId, int alumniId) {
            return base.Channel.GetImageByIdAsync(imageId, alumniId);
        }
        
        public void DeleteImageById(int imageId, int alumniId) {
            base.Channel.DeleteImageById(imageId, alumniId);
        }
        
        public System.Threading.Tasks.Task DeleteImageByIdAsync(int imageId, int alumniId) {
            return base.Channel.DeleteImageByIdAsync(imageId, alumniId);
        }
        
        public void AddImage(AlumniManagement.Frontend.AlumniImageService.ImageDTO[] imageDTO, int alumniId) {
            base.Channel.AddImage(imageDTO, alumniId);
        }
        
        public System.Threading.Tasks.Task AddImageAsync(AlumniManagement.Frontend.AlumniImageService.ImageDTO[] imageDTO, int alumniId) {
            return base.Channel.AddImageAsync(imageDTO, alumniId);
        }
    }
}
