//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlumniManagement.Frontend.AlumniService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AlumniDTO", Namespace="http://schemas.datacontract.org/2004/07/AlumniManagement.WCF.Entities")]
    [System.SerializableAttribute()]
    public partial class AlumniDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AlumniIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateOfBirthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DegreeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> DistrictIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DistrictNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FacultyIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FacultyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> GraduationYearField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[] HobbiesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HobbiesListNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LinkedInProfileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> MajorIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MajorNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MiddleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobileNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ModifiedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhotoNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhotoPathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StateIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AlumniID {
            get {
                return this.AlumniIDField;
            }
            set {
                if ((this.AlumniIDField.Equals(value) != true)) {
                    this.AlumniIDField = value;
                    this.RaisePropertyChanged("AlumniID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateOfBirth {
            get {
                return this.DateOfBirthField;
            }
            set {
                if ((this.DateOfBirthField.Equals(value) != true)) {
                    this.DateOfBirthField = value;
                    this.RaisePropertyChanged("DateOfBirth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Degree {
            get {
                return this.DegreeField;
            }
            set {
                if ((object.ReferenceEquals(this.DegreeField, value) != true)) {
                    this.DegreeField = value;
                    this.RaisePropertyChanged("Degree");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DistrictID {
            get {
                return this.DistrictIDField;
            }
            set {
                if ((this.DistrictIDField.Equals(value) != true)) {
                    this.DistrictIDField = value;
                    this.RaisePropertyChanged("DistrictID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DistrictName {
            get {
                return this.DistrictNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DistrictNameField, value) != true)) {
                    this.DistrictNameField = value;
                    this.RaisePropertyChanged("DistrictName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FacultyID {
            get {
                return this.FacultyIDField;
            }
            set {
                if ((this.FacultyIDField.Equals(value) != true)) {
                    this.FacultyIDField = value;
                    this.RaisePropertyChanged("FacultyID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FacultyName {
            get {
                return this.FacultyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FacultyNameField, value) != true)) {
                    this.FacultyNameField = value;
                    this.RaisePropertyChanged("FacultyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullAddress {
            get {
                return this.FullAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.FullAddressField, value) != true)) {
                    this.FullAddressField = value;
                    this.RaisePropertyChanged("FullAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullName {
            get {
                return this.FullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FullNameField, value) != true)) {
                    this.FullNameField = value;
                    this.RaisePropertyChanged("FullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((object.ReferenceEquals(this.GenderField, value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> GraduationYear {
            get {
                return this.GraduationYearField;
            }
            set {
                if ((this.GraduationYearField.Equals(value) != true)) {
                    this.GraduationYearField = value;
                    this.RaisePropertyChanged("GraduationYear");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] Hobbies {
            get {
                return this.HobbiesField;
            }
            set {
                if ((object.ReferenceEquals(this.HobbiesField, value) != true)) {
                    this.HobbiesField = value;
                    this.RaisePropertyChanged("Hobbies");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HobbiesListName {
            get {
                return this.HobbiesListNameField;
            }
            set {
                if ((object.ReferenceEquals(this.HobbiesListNameField, value) != true)) {
                    this.HobbiesListNameField = value;
                    this.RaisePropertyChanged("HobbiesListName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LinkedInProfile {
            get {
                return this.LinkedInProfileField;
            }
            set {
                if ((object.ReferenceEquals(this.LinkedInProfileField, value) != true)) {
                    this.LinkedInProfileField = value;
                    this.RaisePropertyChanged("LinkedInProfile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MajorID {
            get {
                return this.MajorIDField;
            }
            set {
                if ((this.MajorIDField.Equals(value) != true)) {
                    this.MajorIDField = value;
                    this.RaisePropertyChanged("MajorID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MajorName {
            get {
                return this.MajorNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MajorNameField, value) != true)) {
                    this.MajorNameField = value;
                    this.RaisePropertyChanged("MajorName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MiddleName {
            get {
                return this.MiddleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MiddleNameField, value) != true)) {
                    this.MiddleNameField = value;
                    this.RaisePropertyChanged("MiddleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MobileNumber {
            get {
                return this.MobileNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.MobileNumberField, value) != true)) {
                    this.MobileNumberField = value;
                    this.RaisePropertyChanged("MobileNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ModifiedDate {
            get {
                return this.ModifiedDateField;
            }
            set {
                if ((this.ModifiedDateField.Equals(value) != true)) {
                    this.ModifiedDateField = value;
                    this.RaisePropertyChanged("ModifiedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhotoName {
            get {
                return this.PhotoNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PhotoNameField, value) != true)) {
                    this.PhotoNameField = value;
                    this.RaisePropertyChanged("PhotoName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhotoPath {
            get {
                return this.PhotoPathField;
            }
            set {
                if ((object.ReferenceEquals(this.PhotoPathField, value) != true)) {
                    this.PhotoPathField = value;
                    this.RaisePropertyChanged("PhotoPath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StateID {
            get {
                return this.StateIDField;
            }
            set {
                if ((this.StateIDField.Equals(value) != true)) {
                    this.StateIDField = value;
                    this.RaisePropertyChanged("StateID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StateName {
            get {
                return this.StateNameField;
            }
            set {
                if ((object.ReferenceEquals(this.StateNameField, value) != true)) {
                    this.StateNameField = value;
                    this.RaisePropertyChanged("StateName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HobbyDTO", Namespace="http://schemas.datacontract.org/2004/07/AlumniManagement.WCF.Entities")]
    [System.SerializableAttribute()]
    public partial class HobbyDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HobbyIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HobbyID {
            get {
                return this.HobbyIDField;
            }
            set {
                if ((this.HobbyIDField.Equals(value) != true)) {
                    this.HobbyIDField = value;
                    this.RaisePropertyChanged("HobbyID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StateDTO", Namespace="http://schemas.datacontract.org/2004/07/AlumniManagement.WCF.Entities")]
    [System.SerializableAttribute()]
    public partial class StateDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StateIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StateID {
            get {
                return this.StateIDField;
            }
            set {
                if ((this.StateIDField.Equals(value) != true)) {
                    this.StateIDField = value;
                    this.RaisePropertyChanged("StateID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StateName {
            get {
                return this.StateNameField;
            }
            set {
                if ((object.ReferenceEquals(this.StateNameField, value) != true)) {
                    this.StateNameField = value;
                    this.RaisePropertyChanged("StateName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DistrictDTO", Namespace="http://schemas.datacontract.org/2004/07/AlumniManagement.WCF.Entities")]
    [System.SerializableAttribute()]
    public partial class DistrictDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DistrictIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DistrictNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StateIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DistrictID {
            get {
                return this.DistrictIDField;
            }
            set {
                if ((this.DistrictIDField.Equals(value) != true)) {
                    this.DistrictIDField = value;
                    this.RaisePropertyChanged("DistrictID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DistrictName {
            get {
                return this.DistrictNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DistrictNameField, value) != true)) {
                    this.DistrictNameField = value;
                    this.RaisePropertyChanged("DistrictName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StateID {
            get {
                return this.StateIDField;
            }
            set {
                if ((this.StateIDField.Equals(value) != true)) {
                    this.StateIDField = value;
                    this.RaisePropertyChanged("StateID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AlumniService.IAlumniService")]
    public interface IAlumniService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumniService/GetAll", ReplyAction="http://tempuri.org/IAlumniService/GetAllResponse")]
        AlumniManagement.Frontend.AlumniService.AlumniDTO[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumniService/GetAll", ReplyAction="http://tempuri.org/IAlumniService/GetAllResponse")]
        System.Threading.Tasks.Task<AlumniManagement.Frontend.AlumniService.AlumniDTO[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumniService/GetAllHobbies", ReplyAction="http://tempuri.org/IAlumniService/GetAllHobbiesResponse")]
        AlumniManagement.Frontend.AlumniService.HobbyDTO[] GetAllHobbies();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumniService/GetAllHobbies", ReplyAction="http://tempuri.org/IAlumniService/GetAllHobbiesResponse")]
        System.Threading.Tasks.Task<AlumniManagement.Frontend.AlumniService.HobbyDTO[]> GetAllHobbiesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumniService/GetAllHobbiesByAlumniId", ReplyAction="http://tempuri.org/IAlumniService/GetAllHobbiesByAlumniIdResponse")]
        AlumniManagement.Frontend.AlumniService.HobbyDTO[] GetAllHobbiesByAlumniId(int alumniId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumniService/GetAllHobbiesByAlumniId", ReplyAction="http://tempuri.org/IAlumniService/GetAllHobbiesByAlumniIdResponse")]
        System.Threading.Tasks.Task<AlumniManagement.Frontend.AlumniService.HobbyDTO[]> GetAllHobbiesByAlumniIdAsync(int alumniId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumniService/GetAlumni", ReplyAction="http://tempuri.org/IAlumniService/GetAlumniResponse")]
        AlumniManagement.Frontend.AlumniService.AlumniDTO GetAlumni(int alumniId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumniService/GetAlumni", ReplyAction="http://tempuri.org/IAlumniService/GetAlumniResponse")]
        System.Threading.Tasks.Task<AlumniManagement.Frontend.AlumniService.AlumniDTO> GetAlumniAsync(int alumniId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumniService/InsertAlumni", ReplyAction="http://tempuri.org/IAlumniService/InsertAlumniResponse")]
        void InsertAlumni(AlumniManagement.Frontend.AlumniService.AlumniDTO alumni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumniService/InsertAlumni", ReplyAction="http://tempuri.org/IAlumniService/InsertAlumniResponse")]
        System.Threading.Tasks.Task InsertAlumniAsync(AlumniManagement.Frontend.AlumniService.AlumniDTO alumni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumniService/InsertAlumniWithHobbies", ReplyAction="http://tempuri.org/IAlumniService/InsertAlumniWithHobbiesResponse")]
        void InsertAlumniWithHobbies(AlumniManagement.Frontend.AlumniService.AlumniDTO alumni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumniService/InsertAlumniWithHobbies", ReplyAction="http://tempuri.org/IAlumniService/InsertAlumniWithHobbiesResponse")]
        System.Threading.Tasks.Task InsertAlumniWithHobbiesAsync(AlumniManagement.Frontend.AlumniService.AlumniDTO alumni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumniService/UpdateAlumni", ReplyAction="http://tempuri.org/IAlumniService/UpdateAlumniResponse")]
        void UpdateAlumni(AlumniManagement.Frontend.AlumniService.AlumniDTO alumni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumniService/UpdateAlumni", ReplyAction="http://tempuri.org/IAlumniService/UpdateAlumniResponse")]
        System.Threading.Tasks.Task UpdateAlumniAsync(AlumniManagement.Frontend.AlumniService.AlumniDTO alumni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumniService/UpdateAlumniWithHobbies", ReplyAction="http://tempuri.org/IAlumniService/UpdateAlumniWithHobbiesResponse")]
        void UpdateAlumniWithHobbies(AlumniManagement.Frontend.AlumniService.AlumniDTO alumni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumniService/UpdateAlumniWithHobbies", ReplyAction="http://tempuri.org/IAlumniService/UpdateAlumniWithHobbiesResponse")]
        System.Threading.Tasks.Task UpdateAlumniWithHobbiesAsync(AlumniManagement.Frontend.AlumniService.AlumniDTO alumni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumniService/DeleteAlumni", ReplyAction="http://tempuri.org/IAlumniService/DeleteAlumniResponse")]
        void DeleteAlumni(int alumniId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumniService/DeleteAlumni", ReplyAction="http://tempuri.org/IAlumniService/DeleteAlumniResponse")]
        System.Threading.Tasks.Task DeleteAlumniAsync(int alumniId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumniService/GetDistrictIdByName", ReplyAction="http://tempuri.org/IAlumniService/GetDistrictIdByNameResponse")]
        int GetDistrictIdByName(string districtName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumniService/GetDistrictIdByName", ReplyAction="http://tempuri.org/IAlumniService/GetDistrictIdByNameResponse")]
        System.Threading.Tasks.Task<int> GetDistrictIdByNameAsync(string districtName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumniService/GetStateIdByName", ReplyAction="http://tempuri.org/IAlumniService/GetStateIdByNameResponse")]
        int GetStateIdByName(string stateName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumniService/GetStateIdByName", ReplyAction="http://tempuri.org/IAlumniService/GetStateIdByNameResponse")]
        System.Threading.Tasks.Task<int> GetStateIdByNameAsync(string stateName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumniService/GetAllStates", ReplyAction="http://tempuri.org/IAlumniService/GetAllStatesResponse")]
        AlumniManagement.Frontend.AlumniService.StateDTO[] GetAllStates();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumniService/GetAllStates", ReplyAction="http://tempuri.org/IAlumniService/GetAllStatesResponse")]
        System.Threading.Tasks.Task<AlumniManagement.Frontend.AlumniService.StateDTO[]> GetAllStatesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumniService/GetAllDistricts", ReplyAction="http://tempuri.org/IAlumniService/GetAllDistrictsResponse")]
        AlumniManagement.Frontend.AlumniService.DistrictDTO[] GetAllDistricts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumniService/GetAllDistricts", ReplyAction="http://tempuri.org/IAlumniService/GetAllDistrictsResponse")]
        System.Threading.Tasks.Task<AlumniManagement.Frontend.AlumniService.DistrictDTO[]> GetAllDistrictsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumniService/GetDistrictByStateId", ReplyAction="http://tempuri.org/IAlumniService/GetDistrictByStateIdResponse")]
        AlumniManagement.Frontend.AlumniService.DistrictDTO[] GetDistrictByStateId(int stateId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumniService/GetDistrictByStateId", ReplyAction="http://tempuri.org/IAlumniService/GetDistrictByStateIdResponse")]
        System.Threading.Tasks.Task<AlumniManagement.Frontend.AlumniService.DistrictDTO[]> GetDistrictByStateIdAsync(int stateId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumniService/GetStatesDistrictName", ReplyAction="http://tempuri.org/IAlumniService/GetStatesDistrictNameResponse")]
        string[] GetStatesDistrictName();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumniService/GetStatesDistrictName", ReplyAction="http://tempuri.org/IAlumniService/GetStatesDistrictNameResponse")]
        System.Threading.Tasks.Task<string[]> GetStatesDistrictNameAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumniService/GetMajorFacultiesName", ReplyAction="http://tempuri.org/IAlumniService/GetMajorFacultiesNameResponse")]
        string[] GetMajorFacultiesName();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumniService/GetMajorFacultiesName", ReplyAction="http://tempuri.org/IAlumniService/GetMajorFacultiesNameResponse")]
        System.Threading.Tasks.Task<string[]> GetMajorFacultiesNameAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumniService/ImportFromExcel", ReplyAction="http://tempuri.org/IAlumniService/ImportFromExcelResponse")]
        void ImportFromExcel(AlumniManagement.Frontend.AlumniService.AlumniDTO alumniDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumniService/ImportFromExcel", ReplyAction="http://tempuri.org/IAlumniService/ImportFromExcelResponse")]
        System.Threading.Tasks.Task ImportFromExcelAsync(AlumniManagement.Frontend.AlumniService.AlumniDTO alumniDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumniService/UpsertAlumni", ReplyAction="http://tempuri.org/IAlumniService/UpsertAlumniResponse")]
        void UpsertAlumni(AlumniManagement.Frontend.AlumniService.AlumniDTO alumniDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumniService/UpsertAlumni", ReplyAction="http://tempuri.org/IAlumniService/UpsertAlumniResponse")]
        System.Threading.Tasks.Task UpsertAlumniAsync(AlumniManagement.Frontend.AlumniService.AlumniDTO alumniDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumniService/UpsertMultipleAlumni", ReplyAction="http://tempuri.org/IAlumniService/UpsertMultipleAlumniResponse")]
        void UpsertMultipleAlumni(AlumniManagement.Frontend.AlumniService.AlumniDTO[] alumniDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumniService/UpsertMultipleAlumni", ReplyAction="http://tempuri.org/IAlumniService/UpsertMultipleAlumniResponse")]
        System.Threading.Tasks.Task UpsertMultipleAlumniAsync(AlumniManagement.Frontend.AlumniService.AlumniDTO[] alumniDTO);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAlumniServiceChannel : AlumniManagement.Frontend.AlumniService.IAlumniService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AlumniServiceClient : System.ServiceModel.ClientBase<AlumniManagement.Frontend.AlumniService.IAlumniService>, AlumniManagement.Frontend.AlumniService.IAlumniService {
        
        public AlumniServiceClient() {
        }
        
        public AlumniServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AlumniServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlumniServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlumniServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AlumniManagement.Frontend.AlumniService.AlumniDTO[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<AlumniManagement.Frontend.AlumniService.AlumniDTO[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public AlumniManagement.Frontend.AlumniService.HobbyDTO[] GetAllHobbies() {
            return base.Channel.GetAllHobbies();
        }
        
        public System.Threading.Tasks.Task<AlumniManagement.Frontend.AlumniService.HobbyDTO[]> GetAllHobbiesAsync() {
            return base.Channel.GetAllHobbiesAsync();
        }
        
        public AlumniManagement.Frontend.AlumniService.HobbyDTO[] GetAllHobbiesByAlumniId(int alumniId) {
            return base.Channel.GetAllHobbiesByAlumniId(alumniId);
        }
        
        public System.Threading.Tasks.Task<AlumniManagement.Frontend.AlumniService.HobbyDTO[]> GetAllHobbiesByAlumniIdAsync(int alumniId) {
            return base.Channel.GetAllHobbiesByAlumniIdAsync(alumniId);
        }
        
        public AlumniManagement.Frontend.AlumniService.AlumniDTO GetAlumni(int alumniId) {
            return base.Channel.GetAlumni(alumniId);
        }
        
        public System.Threading.Tasks.Task<AlumniManagement.Frontend.AlumniService.AlumniDTO> GetAlumniAsync(int alumniId) {
            return base.Channel.GetAlumniAsync(alumniId);
        }
        
        public void InsertAlumni(AlumniManagement.Frontend.AlumniService.AlumniDTO alumni) {
            base.Channel.InsertAlumni(alumni);
        }
        
        public System.Threading.Tasks.Task InsertAlumniAsync(AlumniManagement.Frontend.AlumniService.AlumniDTO alumni) {
            return base.Channel.InsertAlumniAsync(alumni);
        }
        
        public void InsertAlumniWithHobbies(AlumniManagement.Frontend.AlumniService.AlumniDTO alumni) {
            base.Channel.InsertAlumniWithHobbies(alumni);
        }
        
        public System.Threading.Tasks.Task InsertAlumniWithHobbiesAsync(AlumniManagement.Frontend.AlumniService.AlumniDTO alumni) {
            return base.Channel.InsertAlumniWithHobbiesAsync(alumni);
        }
        
        public void UpdateAlumni(AlumniManagement.Frontend.AlumniService.AlumniDTO alumni) {
            base.Channel.UpdateAlumni(alumni);
        }
        
        public System.Threading.Tasks.Task UpdateAlumniAsync(AlumniManagement.Frontend.AlumniService.AlumniDTO alumni) {
            return base.Channel.UpdateAlumniAsync(alumni);
        }
        
        public void UpdateAlumniWithHobbies(AlumniManagement.Frontend.AlumniService.AlumniDTO alumni) {
            base.Channel.UpdateAlumniWithHobbies(alumni);
        }
        
        public System.Threading.Tasks.Task UpdateAlumniWithHobbiesAsync(AlumniManagement.Frontend.AlumniService.AlumniDTO alumni) {
            return base.Channel.UpdateAlumniWithHobbiesAsync(alumni);
        }
        
        public void DeleteAlumni(int alumniId) {
            base.Channel.DeleteAlumni(alumniId);
        }
        
        public System.Threading.Tasks.Task DeleteAlumniAsync(int alumniId) {
            return base.Channel.DeleteAlumniAsync(alumniId);
        }
        
        public int GetDistrictIdByName(string districtName) {
            return base.Channel.GetDistrictIdByName(districtName);
        }
        
        public System.Threading.Tasks.Task<int> GetDistrictIdByNameAsync(string districtName) {
            return base.Channel.GetDistrictIdByNameAsync(districtName);
        }
        
        public int GetStateIdByName(string stateName) {
            return base.Channel.GetStateIdByName(stateName);
        }
        
        public System.Threading.Tasks.Task<int> GetStateIdByNameAsync(string stateName) {
            return base.Channel.GetStateIdByNameAsync(stateName);
        }
        
        public AlumniManagement.Frontend.AlumniService.StateDTO[] GetAllStates() {
            return base.Channel.GetAllStates();
        }
        
        public System.Threading.Tasks.Task<AlumniManagement.Frontend.AlumniService.StateDTO[]> GetAllStatesAsync() {
            return base.Channel.GetAllStatesAsync();
        }
        
        public AlumniManagement.Frontend.AlumniService.DistrictDTO[] GetAllDistricts() {
            return base.Channel.GetAllDistricts();
        }
        
        public System.Threading.Tasks.Task<AlumniManagement.Frontend.AlumniService.DistrictDTO[]> GetAllDistrictsAsync() {
            return base.Channel.GetAllDistrictsAsync();
        }
        
        public AlumniManagement.Frontend.AlumniService.DistrictDTO[] GetDistrictByStateId(int stateId) {
            return base.Channel.GetDistrictByStateId(stateId);
        }
        
        public System.Threading.Tasks.Task<AlumniManagement.Frontend.AlumniService.DistrictDTO[]> GetDistrictByStateIdAsync(int stateId) {
            return base.Channel.GetDistrictByStateIdAsync(stateId);
        }
        
        public string[] GetStatesDistrictName() {
            return base.Channel.GetStatesDistrictName();
        }
        
        public System.Threading.Tasks.Task<string[]> GetStatesDistrictNameAsync() {
            return base.Channel.GetStatesDistrictNameAsync();
        }
        
        public string[] GetMajorFacultiesName() {
            return base.Channel.GetMajorFacultiesName();
        }
        
        public System.Threading.Tasks.Task<string[]> GetMajorFacultiesNameAsync() {
            return base.Channel.GetMajorFacultiesNameAsync();
        }
        
        public void ImportFromExcel(AlumniManagement.Frontend.AlumniService.AlumniDTO alumniDTO) {
            base.Channel.ImportFromExcel(alumniDTO);
        }
        
        public System.Threading.Tasks.Task ImportFromExcelAsync(AlumniManagement.Frontend.AlumniService.AlumniDTO alumniDTO) {
            return base.Channel.ImportFromExcelAsync(alumniDTO);
        }
        
        public void UpsertAlumni(AlumniManagement.Frontend.AlumniService.AlumniDTO alumniDTO) {
            base.Channel.UpsertAlumni(alumniDTO);
        }
        
        public System.Threading.Tasks.Task UpsertAlumniAsync(AlumniManagement.Frontend.AlumniService.AlumniDTO alumniDTO) {
            return base.Channel.UpsertAlumniAsync(alumniDTO);
        }
        
        public void UpsertMultipleAlumni(AlumniManagement.Frontend.AlumniService.AlumniDTO[] alumniDTO) {
            base.Channel.UpsertMultipleAlumni(alumniDTO);
        }
        
        public System.Threading.Tasks.Task UpsertMultipleAlumniAsync(AlumniManagement.Frontend.AlumniService.AlumniDTO[] alumniDTO) {
            return base.Channel.UpsertMultipleAlumniAsync(alumniDTO);
        }
    }
}
