//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlumniManagement.Frontend.FacultyService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FacultyDTO", Namespace="http://schemas.datacontract.org/2004/07/AlumniManagement.WCF.Entities")]
    [System.SerializableAttribute()]
    public partial class FacultyDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FacultyIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FacultyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ModifiedDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FacultyID {
            get {
                return this.FacultyIDField;
            }
            set {
                if ((this.FacultyIDField.Equals(value) != true)) {
                    this.FacultyIDField = value;
                    this.RaisePropertyChanged("FacultyID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FacultyName {
            get {
                return this.FacultyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FacultyNameField, value) != true)) {
                    this.FacultyNameField = value;
                    this.RaisePropertyChanged("FacultyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ModifiedDate {
            get {
                return this.ModifiedDateField;
            }
            set {
                if ((this.ModifiedDateField.Equals(value) != true)) {
                    this.ModifiedDateField = value;
                    this.RaisePropertyChanged("ModifiedDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FacultyService.IFacultyService")]
    public interface IFacultyService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFacultyService/GetAll", ReplyAction="http://tempuri.org/IFacultyService/GetAllResponse")]
        AlumniManagement.Frontend.FacultyService.FacultyDTO[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFacultyService/GetAll", ReplyAction="http://tempuri.org/IFacultyService/GetAllResponse")]
        System.Threading.Tasks.Task<AlumniManagement.Frontend.FacultyService.FacultyDTO[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFacultyService/GetFaculty", ReplyAction="http://tempuri.org/IFacultyService/GetFacultyResponse")]
        AlumniManagement.Frontend.FacultyService.FacultyDTO GetFaculty(int FacultyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFacultyService/GetFaculty", ReplyAction="http://tempuri.org/IFacultyService/GetFacultyResponse")]
        System.Threading.Tasks.Task<AlumniManagement.Frontend.FacultyService.FacultyDTO> GetFacultyAsync(int FacultyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFacultyService/GetFacultyIdByName", ReplyAction="http://tempuri.org/IFacultyService/GetFacultyIdByNameResponse")]
        AlumniManagement.Frontend.FacultyService.FacultyDTO GetFacultyIdByName(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFacultyService/GetFacultyIdByName", ReplyAction="http://tempuri.org/IFacultyService/GetFacultyIdByNameResponse")]
        System.Threading.Tasks.Task<AlumniManagement.Frontend.FacultyService.FacultyDTO> GetFacultyIdByNameAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFacultyService/InsertFaculty", ReplyAction="http://tempuri.org/IFacultyService/InsertFacultyResponse")]
        void InsertFaculty(AlumniManagement.Frontend.FacultyService.FacultyDTO Faculty);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFacultyService/InsertFaculty", ReplyAction="http://tempuri.org/IFacultyService/InsertFacultyResponse")]
        System.Threading.Tasks.Task InsertFacultyAsync(AlumniManagement.Frontend.FacultyService.FacultyDTO Faculty);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFacultyService/UpdateFaculty", ReplyAction="http://tempuri.org/IFacultyService/UpdateFacultyResponse")]
        void UpdateFaculty(AlumniManagement.Frontend.FacultyService.FacultyDTO Faculty);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFacultyService/UpdateFaculty", ReplyAction="http://tempuri.org/IFacultyService/UpdateFacultyResponse")]
        System.Threading.Tasks.Task UpdateFacultyAsync(AlumniManagement.Frontend.FacultyService.FacultyDTO Faculty);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFacultyService/DeleteFaculty", ReplyAction="http://tempuri.org/IFacultyService/DeleteFacultyResponse")]
        void DeleteFaculty(int FacultyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFacultyService/DeleteFaculty", ReplyAction="http://tempuri.org/IFacultyService/DeleteFacultyResponse")]
        System.Threading.Tasks.Task DeleteFacultyAsync(int FacultyId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFacultyServiceChannel : AlumniManagement.Frontend.FacultyService.IFacultyService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FacultyServiceClient : System.ServiceModel.ClientBase<AlumniManagement.Frontend.FacultyService.IFacultyService>, AlumniManagement.Frontend.FacultyService.IFacultyService {
        
        public FacultyServiceClient() {
        }
        
        public FacultyServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FacultyServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FacultyServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FacultyServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AlumniManagement.Frontend.FacultyService.FacultyDTO[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<AlumniManagement.Frontend.FacultyService.FacultyDTO[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public AlumniManagement.Frontend.FacultyService.FacultyDTO GetFaculty(int FacultyId) {
            return base.Channel.GetFaculty(FacultyId);
        }
        
        public System.Threading.Tasks.Task<AlumniManagement.Frontend.FacultyService.FacultyDTO> GetFacultyAsync(int FacultyId) {
            return base.Channel.GetFacultyAsync(FacultyId);
        }
        
        public AlumniManagement.Frontend.FacultyService.FacultyDTO GetFacultyIdByName(string name) {
            return base.Channel.GetFacultyIdByName(name);
        }
        
        public System.Threading.Tasks.Task<AlumniManagement.Frontend.FacultyService.FacultyDTO> GetFacultyIdByNameAsync(string name) {
            return base.Channel.GetFacultyIdByNameAsync(name);
        }
        
        public void InsertFaculty(AlumniManagement.Frontend.FacultyService.FacultyDTO Faculty) {
            base.Channel.InsertFaculty(Faculty);
        }
        
        public System.Threading.Tasks.Task InsertFacultyAsync(AlumniManagement.Frontend.FacultyService.FacultyDTO Faculty) {
            return base.Channel.InsertFacultyAsync(Faculty);
        }
        
        public void UpdateFaculty(AlumniManagement.Frontend.FacultyService.FacultyDTO Faculty) {
            base.Channel.UpdateFaculty(Faculty);
        }
        
        public System.Threading.Tasks.Task UpdateFacultyAsync(AlumniManagement.Frontend.FacultyService.FacultyDTO Faculty) {
            return base.Channel.UpdateFacultyAsync(Faculty);
        }
        
        public void DeleteFaculty(int FacultyId) {
            base.Channel.DeleteFaculty(FacultyId);
        }
        
        public System.Threading.Tasks.Task DeleteFacultyAsync(int FacultyId) {
            return base.Channel.DeleteFacultyAsync(FacultyId);
        }
    }
}
