//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlumniManagement.Frontend.MajorService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MajorDTO", Namespace="http://schemas.datacontract.org/2004/07/AlumniManagement.WCF.Entities")]
    [System.SerializableAttribute()]
    public partial class MajorDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> FacultyIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FacultyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MajorIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MajorNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ModifiedDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> FacultyID {
            get {
                return this.FacultyIDField;
            }
            set {
                if ((this.FacultyIDField.Equals(value) != true)) {
                    this.FacultyIDField = value;
                    this.RaisePropertyChanged("FacultyID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FacultyName {
            get {
                return this.FacultyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FacultyNameField, value) != true)) {
                    this.FacultyNameField = value;
                    this.RaisePropertyChanged("FacultyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MajorID {
            get {
                return this.MajorIDField;
            }
            set {
                if ((this.MajorIDField.Equals(value) != true)) {
                    this.MajorIDField = value;
                    this.RaisePropertyChanged("MajorID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MajorName {
            get {
                return this.MajorNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MajorNameField, value) != true)) {
                    this.MajorNameField = value;
                    this.RaisePropertyChanged("MajorName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ModifiedDate {
            get {
                return this.ModifiedDateField;
            }
            set {
                if ((this.ModifiedDateField.Equals(value) != true)) {
                    this.ModifiedDateField = value;
                    this.RaisePropertyChanged("ModifiedDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MajorService.IMajorService")]
    public interface IMajorService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMajorService/GetAll", ReplyAction="http://tempuri.org/IMajorService/GetAllResponse")]
        AlumniManagement.Frontend.MajorService.MajorDTO[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMajorService/GetAll", ReplyAction="http://tempuri.org/IMajorService/GetAllResponse")]
        System.Threading.Tasks.Task<AlumniManagement.Frontend.MajorService.MajorDTO[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMajorService/GetMajor", ReplyAction="http://tempuri.org/IMajorService/GetMajorResponse")]
        AlumniManagement.Frontend.MajorService.MajorDTO GetMajor(int majorId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMajorService/GetMajor", ReplyAction="http://tempuri.org/IMajorService/GetMajorResponse")]
        System.Threading.Tasks.Task<AlumniManagement.Frontend.MajorService.MajorDTO> GetMajorAsync(int majorId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMajorService/GetMajorIdByName", ReplyAction="http://tempuri.org/IMajorService/GetMajorIdByNameResponse")]
        AlumniManagement.Frontend.MajorService.MajorDTO GetMajorIdByName(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMajorService/GetMajorIdByName", ReplyAction="http://tempuri.org/IMajorService/GetMajorIdByNameResponse")]
        System.Threading.Tasks.Task<AlumniManagement.Frontend.MajorService.MajorDTO> GetMajorIdByNameAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMajorService/GetMajorIdByFacultyId", ReplyAction="http://tempuri.org/IMajorService/GetMajorIdByFacultyIdResponse")]
        AlumniManagement.Frontend.MajorService.MajorDTO[] GetMajorIdByFacultyId(int facultyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMajorService/GetMajorIdByFacultyId", ReplyAction="http://tempuri.org/IMajorService/GetMajorIdByFacultyIdResponse")]
        System.Threading.Tasks.Task<AlumniManagement.Frontend.MajorService.MajorDTO[]> GetMajorIdByFacultyIdAsync(int facultyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMajorService/InsertMajor", ReplyAction="http://tempuri.org/IMajorService/InsertMajorResponse")]
        void InsertMajor(AlumniManagement.Frontend.MajorService.MajorDTO major);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMajorService/InsertMajor", ReplyAction="http://tempuri.org/IMajorService/InsertMajorResponse")]
        System.Threading.Tasks.Task InsertMajorAsync(AlumniManagement.Frontend.MajorService.MajorDTO major);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMajorService/UpdateMajor", ReplyAction="http://tempuri.org/IMajorService/UpdateMajorResponse")]
        void UpdateMajor(AlumniManagement.Frontend.MajorService.MajorDTO major);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMajorService/UpdateMajor", ReplyAction="http://tempuri.org/IMajorService/UpdateMajorResponse")]
        System.Threading.Tasks.Task UpdateMajorAsync(AlumniManagement.Frontend.MajorService.MajorDTO major);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMajorService/DeleteMajor", ReplyAction="http://tempuri.org/IMajorService/DeleteMajorResponse")]
        void DeleteMajor(int majorId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMajorService/DeleteMajor", ReplyAction="http://tempuri.org/IMajorService/DeleteMajorResponse")]
        System.Threading.Tasks.Task DeleteMajorAsync(int majorId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMajorServiceChannel : AlumniManagement.Frontend.MajorService.IMajorService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MajorServiceClient : System.ServiceModel.ClientBase<AlumniManagement.Frontend.MajorService.IMajorService>, AlumniManagement.Frontend.MajorService.IMajorService {
        
        public MajorServiceClient() {
        }
        
        public MajorServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MajorServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MajorServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MajorServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AlumniManagement.Frontend.MajorService.MajorDTO[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<AlumniManagement.Frontend.MajorService.MajorDTO[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public AlumniManagement.Frontend.MajorService.MajorDTO GetMajor(int majorId) {
            return base.Channel.GetMajor(majorId);
        }
        
        public System.Threading.Tasks.Task<AlumniManagement.Frontend.MajorService.MajorDTO> GetMajorAsync(int majorId) {
            return base.Channel.GetMajorAsync(majorId);
        }
        
        public AlumniManagement.Frontend.MajorService.MajorDTO GetMajorIdByName(string name) {
            return base.Channel.GetMajorIdByName(name);
        }
        
        public System.Threading.Tasks.Task<AlumniManagement.Frontend.MajorService.MajorDTO> GetMajorIdByNameAsync(string name) {
            return base.Channel.GetMajorIdByNameAsync(name);
        }
        
        public AlumniManagement.Frontend.MajorService.MajorDTO[] GetMajorIdByFacultyId(int facultyId) {
            return base.Channel.GetMajorIdByFacultyId(facultyId);
        }
        
        public System.Threading.Tasks.Task<AlumniManagement.Frontend.MajorService.MajorDTO[]> GetMajorIdByFacultyIdAsync(int facultyId) {
            return base.Channel.GetMajorIdByFacultyIdAsync(facultyId);
        }
        
        public void InsertMajor(AlumniManagement.Frontend.MajorService.MajorDTO major) {
            base.Channel.InsertMajor(major);
        }
        
        public System.Threading.Tasks.Task InsertMajorAsync(AlumniManagement.Frontend.MajorService.MajorDTO major) {
            return base.Channel.InsertMajorAsync(major);
        }
        
        public void UpdateMajor(AlumniManagement.Frontend.MajorService.MajorDTO major) {
            base.Channel.UpdateMajor(major);
        }
        
        public System.Threading.Tasks.Task UpdateMajorAsync(AlumniManagement.Frontend.MajorService.MajorDTO major) {
            return base.Channel.UpdateMajorAsync(major);
        }
        
        public void DeleteMajor(int majorId) {
            base.Channel.DeleteMajor(majorId);
        }
        
        public System.Threading.Tasks.Task DeleteMajorAsync(int majorId) {
            return base.Channel.DeleteMajorAsync(majorId);
        }
    }
}
